### ISSUE TITLE
Transformer Version

### ISSUE THREAD

**Issue by ZiqianZENG** [ZihanWangKi/XClass#5]
Dear authors

Thanks for sharing your codes. When I was running train_text_classifier.py
I got some errors, and I would like to ask **which version of transformers** you are using. Thank you very much. 
Traceback (most recent call last):
  File "train_text_classifier.py", line 681, in <module>
    main()
  File "train_text_classifier.py", line 634, in main
    train_dataset = load_and_cache_examples(args, args.task_name, tokenizer, evaluate=False)
  File "train_text_classifier.py", line 386, in load_and_cache_examples
    features = convert_examples_to_features(
  File "~/site-packages/transformers/data/processors/glue.py", line 72, in glue_convert_examples_to_features
    return _glue_convert_examples_to_features(
  File "~/site-packages/transformers/data/processors/glue.py", line 143, in _glue_convert_examples_to_features
    batch_encoding = tokenizer(
  File "~/site-packages/transformers/tokenization_utils_base.py", line 2318, in __call__
    return self.batch_encode_plus(
  File "~/transformers/tokenization_utils_base.py", line 2503, in batch_encode_plus
    return self._batch_encode_plus(
  File "~/site-packages/transformers/tokenization_utils_fast.py", line 375, in _batch_encode_plus
    encodings = self._tokenizer.encode_batch(
TypeError: TextInputSequence must be str

**Comment by ZihanWangKi** [comment]
Hi Ziqian,

Please try transformers==3.0.2. I will make an update to the requirements.txt. Thanks for pointing out!

**Comment by ZiqianZENG** [comment]
Thank you very much!
